const String page PROGMEM = "<head>"
            " <meta name='viewport' content='width=device-width, initial-scale=1.0'>"
            " <script src='https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js'></script>"
            " <script src='/jscript.js'></script>"
            " <link href='https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap' rel='stylesheet'>"
            " <style>"
            "   body{"
            " background-color:aqua;"
            " font-family: 'Roboto', sans-serif;" 
            "}"
            "#turbidity{"
            " margin-left:50px;"
            " width:100px;" 
            " height:200px;"
            " border:1px solid gray;"
            " border-radius:10px;"
            " transition: background-color 2s;"
            "}"
            "#tur-value{ "
            "  width:50px;"
            "}"
            "#esp32{"
            "  width:60%;"
            "  margin-left:0%;"
            "}"
            "#tmm-logo{"
            "  width:50%;"
            "}"
            "</style>"
            " </head>"
            " <body>"
            " <h1>ESP32 Turbidity Sensor</h1>"
            " <p>Uses a NodeMCU-32S and Gravity Turbidity Sensor from DFRobot</p>"
            " <p><a href='https://www.teachmemicro.com/esp32-turbidity-sensor'>Full tutorial</a></p>"
            " <label for='tur-value'>Turbidity:</label> <input type='text' id='tur-value'>""</p>\r\n" 
            " <table><tr><td><div id='turbidity'></div>"
            " </td><td><img id='esp32' src='https://i.imgur.com/dbHpU9s.png'></td></tr>"
            " <tr><td style='text-align:center;'>1-clear, 5-very muddy</td><td style='text-align:right;'><img id='tmm-logo' src='https://i.imgur.com/G80eVhL.png' /></td></tr></table>"
            "</body>";
